### ISSUE TITLE
A few issues with Atom text editor (don't laugh, some people still use Atom..lol)

### ISSUE THREAD

**Issue by Darksubject84** [btholt/complete-intro-to-react-v5#112]
I just finished this course and it took me a few days longer then I wanted because I had to do some major workarounds and pretty much sleep on StackOverflow, since I'm obviously not a guru-level coder yet. As the project got bigger, and more  workarounds we're introduced, they effectively compounded onto each other and towards the end I couldn't even write the same code as him. I had to understand what the intentions were, then translate them in a way that worked with the existing workarounds and workflow. At first I was annoyed that I had to keep pausing, debugging, rewinding, redoing git commits but now that I'm finished and it FINALLY works like advertised, I'm proud of myself for toughening it out and fixing those issues because I learned a TON from just figuring out the problem was and side-stepping them one at a time. I'll write the issue and then I'll say my workaround (or lack thereof) for the major issues, maybe there are better ways to fix them for Atom. 

1.) Prettier/eslint configuration nightmare - The best formatter for Atom is Beautifier, which still allows you to pick and choose which formatter you want with what for each language, given that I uninstalled it and did a clean set-up  with Brian's tools because he's AWESOME with tool configurations and said I'll try it. I couldn't for the life of me get BOTH prettier and eslint to work together within atom, either one or the other worked at a given moment, but not both. Plus, Atom has this weird open ticket issue with Prettier that it collapses multi-line attributes in self closing tags into a single line (can you imagine an input element with 7 attributes all on a single line, reformatting the same way on save? You gotta scroll like 50 yards to the right to even close the tag).  
SOLUTION: I finally gave up and uninstalled prettier and used eslint with Beautifier, which then worked exactly like his set-up. Prettier is a no-go for Atom unless your boss like Brian.

2.) Babel Experimental feature for replacing Constructor/super boilerplate code for component classes messed up the value of THIS for the rest of the course for me. I couldn't use es6 arrow functions on component methods because this got screwed up after the install. And for some of the methods I even had to bind them in the constructor to finally work because something else invoked them (somehow). Arrow functions only worked in self-contained event handlers (sometimes, get to more on that later). Maybe I installed or configured it wrong, but that's way to much headache to avoid writing a few lines of code with every component. I even tried a completely clean install and git-fast forward too, which THEN had me hunting for all the previous workarounds I did beforehand because the commits are not configured for Atom use. I didn't use git until AFTER this, so I couldn't rewind and uninstall it,  so I was not enthusiastic about starting over from the beginner the third time. Which DID re-affirm my resolve to use git on EVERY course now.
SOLUTION: I just kept the experimental install, but removed all babel plugins and presets, kept an empty object in the .babelrc, used the constructor/super boilerplate code and used a combo of function declarations and method binding for the rest of the course. Fortunately I'm used to prop-drilling from Code-Academy's Pro react course, so THIS wasn't too bad for me.

3.) ErrorBoundary component was not returning the children - Another long nightmare, never solved it. Error for some reason was not returning the children that I was trying to pass though it, so it either not rendered at all or got stuck on the loading page because the props didn't pass through and component didn't update. This was pretty advanced for an intro course but I stuck with it as long as I could until I gave up. I have no idea what went wrong with that, there isn't a lot of support for Atom configuration (why the hell did I choose atom a couple years ago when I first went back to school? I'm so used to it now and can emulate nearly everything VScode does, but it requires intense knowledge of a WIDE variety of topics to configure tools to work together). It's like switching over to linux for the first time, HORRIBLE learning curve, but elite-snooty feeling afterwards. Except in this case... Now I just feel dumb...
SOLUTION: None, I wrote out the code but never imported it into other modules. For errors on asynchronous code, I switched from async to fetch, and used it's in-built error methods to handle them. Which came with it's on set of problems, but solvable.

4.) Lastly, the ThemeContext instance in Details js switched the context of this again. (It was already messed up from earlier, then it twisted it again). Any area of JSX where I had to put in brackets and write vanilla javascript expressions in regards to the theme, was just haywire. Arrow functions didn't work like the previous workaround, neither did binding them. Ternary operator was selective at best. Props got lost somewhere in the Thousand layers of Router children and 
SOLUTION: I used separate event handler functions, in combination with MANY class bindings and selective arrow functions to control the context of WHERE events gets called and WHEN expressions got evaluated. For instance, In details.js working on the modal button between ThemeContext tags, I had to create functions declarations for toggleModal and adopt class methods, bind both of them to the constructor, created a seperate event handler function that was also bound to this class, stuck it in the button onClick attribute and destructed theme from ThemeContext into a variable which I placed in an array on state with the button click event, then created a boolean value isThemeCaptured in state which the onclick toggled, then placed the toggleModal and adopt methods in componentDidUpdate lifecycle method which conditionally ran the methods when the boolean was true and  because state was updated. All for a fancy alert screen. The style theme worked like a charm for some reason, it was only event delegation that was the nightmare.

If I was boss level on tool configuration like Brian Holt, then I'm sure ALL of these issues would have required simple additions instead of massive workarounds and spaghetti code "Macgyvered" together with a toothpick, bubble-gum and decarbonated Dr. Pepper. I didn't show any screenshots because frankly I'm embarrassed how ugly my code looks, and I totally went against best practices which probably would have bankrupted my company (like using props to update state, YIKES!) and it'll give anyone a headache trying to read it. Just fought through it so hard that I had to share. Please, Please, PLEASE introduce some alternatives for Atom users, if it's not too much work for you guys. Ok, I'll show a small screenshot so you guys can see a little bit.
![Github react pic for issue](https://user-images.githubusercontent.com/24361554/90855792-777f3100-e34e-11ea-9107-e6e347c14904.PNG)

**Comment by 1Marc** [comment]
Thanks for the suggestion,  I don't think we have plans to test our courses with Atom at this point but I can mention it to our teachers to remember people use other text editors.
