### ISSUE TITLE
Breeds data not fetched, error to get the breeds from the @front end masters api

### ISSUE THREAD

**Issue by Yael95** [btholt/complete-intro-to-react-v5#115]
When i try to get the breeds, the connection times out and I don't get the data demanded, can you please help me fix this issue as I cannot advance in the course, I am on the effects section of the complete intro to react v5.

**Comment by shaw64489** [comment]
Same

**Comment by 1Marc** [comment]
Perhaps there was an outage. We'll investigate further but it appears to be working fine right now:

<img width="1305" alt="breeds" src="https://user-images.githubusercontent.com/19269/96008998-be951a00-0e05-11eb-9b70-c01635afc075.png">
