### ISSUE TITLE
Mapping not rendering img tag.

### ISSUE THREAD

**Issue by fabrizzioalco** [btholt/complete-intro-to-react-v5#118]
When you map into the <img> in the Carousel.tsx, the image is not rendered because it needs  a return(). 

`photos.map((photo, index)=>{
      return(
       <img 
         key={photo}
         onClick={this.handleIndexClick}
         data-index={index}
          src={photo}
          className={index === active ? "active" : ""}
           alt="animal thumbnail"
      />

    )
})`

this was how i fixed that issue, if theres anyone that this code worked perfectly for you, can you tell me why it didn't worked for please

**Comment by aashiqahmed98** [comment]
Try leaving the curly braces and return

**Comment by goodhands** [comment]
@fabrizzioalco that is because you are using a curly brace instead of a bracket. This should work:
````js
photos.map((photo, index)=>(
 <img
  key={photo}
  onClick={this.handleIndexClick}
  data-index={index}
  src={photo}
  className={index === active ? "active" : ""}
  alt="animal thumbnail"
/>
))`
````

**Comment by fabrizzioalco** [comment]
Thank you! i shouldn't put curly braces or it's optional?

**Comment by goodhands** [comment]
Don't put the curly braces. The snippet above should work.

**Comment by aashiqahmed98** [comment]
I think we can close this Issue @btholt  @1Marc

**Comment by btholt** [comment]
Thank you!
