### ISSUE TITLE
Input components lose focus in custom hooks

### ISSUE THREAD

**Issue by sudo-kaizen** [btholt/complete-intro-to-react-v5#126]
I noticed that input components lose focus after a state change in custom
hooks. This happened in the `useDropdown` hook. After an option is selected,
the select dropdown loses focus.

This also happened with an input element in a custom hook I created in a 
little project I  made. Here's the code:

```javascript
import React, {useState } from 'react';

export default function useTextInput(defaultValue, id, placeholder) {
  const [val, setVal] = useState(defaultValue);

  const TextInput = ({ children }) => {
    return (
      <>
        <label
          htmlFor={id}
        >
          {children}
          <input
            value={val}
            onChange={e => setVal(e.target.value)}
            type="text"
            id={id}
            placeholder={placeholder}
          />
        </label>
      </>
    );
  };

  return [val, TextInput];
```
Whenever there's a change in the value of `<TextInput />`, it loses focus and I cannot change
its value further until I focus on the component again.

I feel this has to do with how React's lifecycle:` UI -> side-effect -> state change -> re-render`
and because of the re-rendering, the input component loses focus.

Is this a problem with React or it is not proper to use UI components like `<input/> in custom hooks?

**Comment by panlazy** [comment]
Reason of this you are re-rendering entire component (`input`) on state change. If you google it you'll find bunch of resources about that. Check this to get an idea. https://stackoverflow.com/questions/56758864/input-is-loosing-focus-on-hooks-update

**Comment by sudo-kaizen** [comment]
Thanks @panlazy

It was used in the course for the `select` input element and I thought I could use it with input too, and then I discovered that.

It's quite an insight. Thanks again.
