### ISSUE TITLE
Parcel and emotion.js error

### ISSUE THREAD

**Issue by yanuwarishak** [btholt/complete-intro-to-react-v5#130]
In part 13 following the set up for emotion I got this error in console and the application returns "not rendered"
`Uncaught Error: The "@emotion/core" package has been renamed to "@emotion/react". Please import it like this import { jsx } from "@emotion/react"`

However changing import to '@emotion/react' create another error which most likely have somethin to do with environment variable, the error is as following:
`NavBar.js:10 Uncaught ReferenceError: process is not defined`

**Comment by yanuwarishak** [comment]
I found a fix from stackoverflow by modifying the "plugins" in .babelrc to this:
```
  "plugins": [
    "transform-inline-environment-variables",
    "@babel/plugin-proposal-class-properties"
  ]
```

**Comment by TheCoderSingh** [comment]
> I found a fix from stackoverflow by modifying the "plugins" in .babelrc to this:
> 
> ```
>   "plugins": [
>     "transform-inline-environment-variables",
>     "@babel/plugin-proposal-class-properties"
>   ]
> ```

Thanks a lot!
