### ISSUE TITLE
useInput example

### ISSUE THREAD

**Issue by blong824** [btholt/complete-intro-to-react-v5#20]
Hi,
  I followed along with the course and it was great.  I started my own project and am abstracting selects, inputs, check boxes, etc into their own hooks.

The useDropdown you created works great.  I tried to create a useInput.  I keep the state in the parent and pass in the default Value and and update function.  It gets updated but then loses focus on rerender.  I spent some time searching stackoverflow with no luck.  I've seen other packages keep the input in the component and just have state in the hook.  

Is it possible for you to create a useInput hook to show how we can accomplish this following the same pattern as useDropdown?

Example of my useInput:
```
import React from "react";

const useInput = (type, label, name, defaultValue, handleChange) => {
  const onChange = e => {
    const { name, value } = e.target;
    handleChange({ [name]: value });
  };

  const Input = () => (
    <label htmlFor={name}>
      {label}
      <input
        id={name}
        type={type}
        name={name}
        value={defaultValue}
        onChange={onChange}
        onBlur={onChange}
      />
    </label>
  );

  return Input;
};

export default useInput;

```

Thank you

**Comment by 1Marc** [comment]
It's something you could do, yes -- but since this is an extra question and not an issue with the course, I'm closing the issue.
