### ISSUE TITLE
"Portals and Refs" section and "Context" section of website are out of order

### ISSUE THREAD

**Issue by ccherot** [btholt/complete-intro-to-react-v5#21]
This is just a quick note to point out that in the website for this course, two of the sections are out of order it seems.  The commit for the Context section has code from the Portals and Refs section which comes after the Context section.  Just a small detail I wanted to point as it was slightly confusing.

**Comment by 1Marc** [comment]
They're not out of order, there just isn't individual commits for context and portals -- they're combined into one commit.
