### ISSUE TITLE
mersenne.js:276 Uncaught Error: seed(S) must take numeric argument; is string

### ISSUE THREAD

**Issue by blade-demon** [btholt/complete-intro-to-react-v5#25]
I got a error caused by the “Details” Component. It seems that the parameter **this.props.id** pass to **pet.animal** is wrong.

```JS
import React from 'react';
import pet from '@frontendmasters/pet';

class Details extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: true
    };
  }

  componentDidMount() {
    pet
      .animal(this.props.id)
      .then(({ animal }) => {
        this.setState({
          name: animal.name,
          animal: animal.type,
          location: `${animal.contact.address.city}, ${animal.contact.address.state}`,
          description: animal.description,
          media: animal.photos,
          breed: animal.breeds.primary,
          loading: false
        });
      })
      .catch(err => this.setState({ error: err }));
  }
  render() {
    if (this.state.loading) {
      return (<h1>loading … </h1>);
    }

    const { animal, breed, location, description, name } = this.state;

    return (
      <div className="details">
        <div>
          <h1>{name}</h1>
          <h2>{`${animal} — ${breed} — ${location}`}</h2>
          <button>Adopt {name}</button>
          <p>{description}</p>
        </div>
      </div>
    );
  }
}
export default Details;
```
![屏幕快照 2019-07-09 23 52 53](https://user-images.githubusercontent.com/8427848/60903940-c8e07400-a2a4-11e9-9233-407ebe6f8014.png)

**Comment by 1Marc** [comment]
I can't debug you individual issue -- you'll have to look through the commit diffs on May 1 https://github.com/btholt/complete-intro-to-react-v5/commits/master and find the code closest to where you're at in the course to compare. 

The site also walks you through the code and commits are linked to along the way: https://btholt.github.io/complete-intro-to-react-v5/

**Comment by nickalcantara** [comment]
Ran into the same issue; wrapping it in a parseInt fixed it.

`  componentDidMount() {
    /*
      instead of getting as an argument, get it from parent via props.
      props is immutable; a child can't change its parents props.
      arrow funcs are "required" in class components.
      this is because function() will create a new context
      and prevent our access to 'this'.
    */
    pet.animal(parseInt(this.props.id)).then(({ animal }) => {
      this.setState({
        name: animal.name,
        animal: animal.type,
        location: `${animal.contact.address.city}, ${animal.contact.address.state}`,
        description: animal.description,
        media: animal.photos,
        breed: animal.breeds.primary,
        loading: false
      });
    }, console.error);
  }`

**Comment by nickjamesnorris** [comment]
@nickalcantara This worked for me, thanks.

**Comment by yashguptaz** [comment]
Or just add a `(+this.props.id)`
