### ISSUE TITLE
Breeds names are strange

### ISSUE THREAD

**Issue by lukasab** [btholt/complete-intro-to-react-v5#40]
I was following the videos and then I noticed that the breeds' names were strange. 

I thought that I made something wrong so I cloned the repo did `git checkout 9d52149`, `npm install` and `npm run dev:mock` but the error was this there.

Here is a picture with the names of the breeds:
![Captura de Tela 2019-09-13 às 23 41 35](https://user-images.githubusercontent.com/16520334/64902609-af7eee00-d680-11e9-962f-c93d9455ef87.png)

**Comment by PhilippSchweizer** [comment]
Hi @lukasab. Thats because you used the mock mode. If you run `npm run dev` you will see normal breed names.
