### ISSUE TITLE
Curious question: adopt url is not the real adopt url ?😊

### ISSUE THREAD

**Issue by luml** [btholt/complete-intro-to-react-v5#49]
age: "Baby"
​​
attributes: Object { spayed_neutered: true, house_trained: false, special_needs: true, … }
​​
breeds: Object { primary: "Libyan Dinar", mixed: false, unknown: true, … }
​​
coat: "Medium"
​​
colors: Object { primary: "pink", secondary: "lavender", tertiary: null }
​​
contact: Object { email: "Lillie86@gmail.com", phone: "1-509-753-1314", address: {…}, … }
​​
description: "Et ipsum sed autem. Voluptate iure dolore. Ut quod sit suscipit laudantium quaerat quia. Inventore voluptates a. Officia dolorum amet ipsa. Qui fugit sunt est voluptatem ut odio quos."
​​
environment: Object { children: true, dogs: true, cats: null }
​​
gender: "Male"
​​
id: 9468194
​​
name: "Johnpaul"
​​
organization_id: "TN168"
​​
photos: Array [ {…}, {…} ]
​​
published_at: "1970-01-01T00:00:00.000Z"
​​
size: "Large"
​​
species: "cat"
​​
status: "adoptable"
​​
tags: Array []
​​
type: "cat"
​​
url: "https://frontendmasters.com/?ref=pet"

**Comment by 1Marc** [comment]
If the API doesn't have a URL, it adds in a URL so that the API doesn't send back empty / broken data.

As far as I know.. all of the rest of the data is real. It is just cached.

**Comment by 1Marc** [comment]
Oh.. Brian said that you might be running the API in mock/offline mode, which makes all of the URLs return FrontendMasters.com URLs.
