### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by DanielDawidowski** [btholt/complete-intro-to-react-v5#56]
After configuring and installing babel packages. I recieve this ugly error

> C:\Users\Daniel\Desktop\Adopt ME\src\App.js: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this 
error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

package.json
`"devDependencies": {
    "@babel/cli": "^7.7.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.7.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.3",
    "cross-env": "^6.0.3",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "^2.1.2",
    "parcel-bundler": "^1.9.7",
    "prettier": "^1.18.2"
  },
  "dependencies": {
    "@frontendmasters/pet": "^1.0.3",
    "@reach/router": "^1.2.1",
    "react": "^16.11.0",
    "react-dom": "^16.11.0"
  },`
Installing @babel/cli & babel-core": "^7.0.0-bridge.0 give back sam error.

Anyone knows how to handle this error?

**Comment by csisoap** [comment]
Try `npm ci`. It will download everything that match with the version on it.

**Comment by DanielDawidowski** [comment]
Unfortunately same error.

**Comment by huynhthetong** [comment]
Actually You have a problem with Parcel@1.9.7. You should update parcel latest and install @babel/plugin-transform-runtime. It'll fix your problem.

**Comment by DanielDawidowski** [comment]
Thx `huynhthetong` . That works but not with latest version of Parcel.
