### ISSUE TITLE
ThemeContext problem

### ISSUE THREAD

**Issue by ellenripley4** [btholt/complete-intro-to-react-v5#60]
Hello, Brian. In "Persisting state with Context Hooks" part of video course on Frontend Masters, you resolved the problem with ThemeContext by fixing `<a>` tag to `<Link>` tag on the `Details.js` page. But you did not provide this fix in your guide, so when people are copying code from your guide without watching a course, they will encounter this problem too.

**Comment by 1Marc** [comment]
Not sure where in the website this should be added. Feel free to open a PR in the `gh-pages-src` branch where this should be updated.
