### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by huynhthetong** [btholt/complete-intro-to-react-v5#68]
Why I get this problem. When I refresh page Details (server render) I get this. I hope you and everyone give some solutions to solve this problem. I thank you, guys!
![image](https://user-images.githubusercontent.com/19568463/70966802-fe488380-20c6-11ea-8cd0-db784914b91f.png)

**Comment by 1Marc** [comment]
Please see the solution here: https://github.com/btholt/complete-intro-to-react-v4/issues/3#issuecomment-425124265
