### ISSUE TITLE
A breeds API from @frontendmasters/pet is not working

### ISSUE THREAD

**Issue by vudhidej-d** [btholt/complete-intro-to-react-v5#71]
I just start a Complete Intro to React v5 course today. And after I arrived at an `Effects` section, I found a breeds API is not working

It is able to install a package and use `ANIMALS` data. However, a request that sent to an endpoint of a breeds API is timeout.
![image](https://user-images.githubusercontent.com/57282605/72203608-5729f280-34a0-11ea-8eab-30ba6d507fde.png)

So, I going to see a `@frontendmasters/pet` repository to find some solution but found a repo is broken
```
https://github.com/FrontendMasters/pet
```

What can I do for continuing a course? Or I should mock data by myself.

**Comment by fmquaglia** [comment]
@vudhidej-d in the course Brian mentions the API goes down from time to time.
T[esting now in runkit](https://npm.runkit.com/%40frontendmasters%2Fpet) and it seems to be working now.

The repo is probably private because it isn't listed in @FrontendMasters Github profile

**Comment by btholt** [comment]
You can always put the API into mock mode by setting `PET_MOCK` to `mock` in your dev environment and it'll mock the whole API.

In any case, thanks for the report.

**Comment by MasoodUX** [comment]
@btholt how can I resolve "./node_modules/@frontendmasters/pet/impl.js
Module not found: Can't resolve 'axios' in 'C:\Users\lenovo\Desktop\reactjs\beta\node_modules\@frontendmasters\pet'
"
