### ISSUE TITLE
label.replace is not a function

### ISSUE THREAD

**Issue by harithzamri** [btholt/complete-intro-to-react-v5#73]
I just start a Complete Intro to React v5 course today. And after I arrived at an `Dropdown` section, I found out an error which it says label.replace is not a function. Any idea what cause is it?

![Capture](https://user-images.githubusercontent.com/37389526/73910396-2c3d8d80-48ea-11ea-93ed-4a9a31af32af.PNG)

**Comment by alvinlal** [comment]
you may not be passing a string to the label argument,
make sure you pass a string(something that is enclosed in double or single quotes) while calling the
useDropdown function from the SearchParams.js file,
for example:-`const [animal, Animaldropdown] = useDropdown("animal", "dog", ANIMALS);`
here,the string animal will be passed to the label parameter in useDropdown.

**Comment by sangampokharel** [comment]
pet.breeds("dog").then(console.log,console.error) not returning data ???

**Comment by harithzamri** [comment]
You are exactly right. I already know what is the problem. Thanks ^.^

**Comment by btholt** [comment]
Thanks @alvinlal! Glad you were able to resolve your issue @harithzamri.
