### ISSUE TITLE
@frontendmasters/pet API not working

### ISSUE THREAD

**Issue by sangampokharel** [btholt/complete-intro-to-react-v5#74]
import React {useEffect} from 'react';
import pet, { ANIMALS } from "@frontendmasters/pet";

useEffect(() => {
  pet.breeds("dog").then(console.log, console.error);  //not getting data 
},[]);

**Comment by btholt** [comment]
I just checked and we haven't had any downtime so I'd check your code in other places. The API is definitely working at this moment in time.

If it still isn't working for you, you can start the API client in mock mode if you set the `PET_MOCK` environment variable to `mock`
